name: directory
description: Servian directory application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  logger: ^1.1.0
  introduction_screen: ^3.0.0
  flutter_signin_button: ^2.0.0
  google_sign_in: ^5.2.4
  firebase_core: ^1.13.1
  firebase_auth: ^3.3.11
  cloud_firestore: ^3.1.10
  firebase_crashlytics: ^2.5.3
  firebase_analytics: ^9.1.2
  firebase_performance: ^0.8.0+7
  path_provider: ^2.0.9
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  bloc_test: ^9.0.3
  firebase_auth_oauth: ^1.2.0
  shared_preferences: ^2.0.13
  flutter_secure_storage: ^5.0.2
  url_launcher: ^6.0.20
  cupertino_icons: ^1.0.4
  get_it: ^7.2.0
  loading_overlay: ^0.3.0
  connectivity_plus: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  flutter_launcher_icons: ^0.9.2
  flutter_app_name: ^0.1.1
  flutter_native_splash: ^2.1.2+1
  flutter_lints: ^1.0.4
  mockito: ^5.1.0
  build_runner: ^2.1.8 # -> flutter pub run build_runner build

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/app_logo.png
    - assets/splash.png
    - assets/introduction/ # introduction images

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"
  remove_alpha_ios: true
  # commands -> flutter pub get && flutter pub run flutter_launcher_icons:main

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash.png
  dark_color: "#000000"
  #dark_image: assets/splash_dark.png
  android: true
  ios: true
  # android_gravity: full,
  # ios_content_mode: scaleAspectFill
  # commands -> flutter clean && flutter pub get && flutter pub run flutter_native_splash:create


flutter_app_name:
  name: "Servian Directory"
  # commands -> flutter pub get && flutter pub run flutter_app_name